# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

#services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

services:
    app.tokens.action_listener:
        class: AppBundle\EventListener\RestEventController
        arguments: [ "@doctrine.orm.entity_manager" , "@router" ]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
